app/routes/habit.py
from app.models import db, Habit
from app.forms import AddHabitForm, UpdateHabitForm
from app.functions.openai.answer_question import answer_question
from app.functions.thyme.helpers.habits import get_habit, get_habits
from app.functions.thyme.helpers.user import get_user_from_thyme
from flask import Blueprint, redirect, url_for, render_template, session
from app.forms import AskQuestionForm
from app.functions.thyme.helpers.forms import prepopulate_form
from app.constants.general import APOLOGY

bp = Blueprint("habit", __name__, url_prefix="/habit")

# -----------
# ADD 
# -----------
@bp.route("/add", methods=["GET", "POST"])
def add():
    form = AddHabitForm()
    if form.validate_on_submit():
       handle_add_habit(form)
       return redirect(url_for("home.preferences"))
    return render_template("/components/forms/form.html", title="Add Habit", form=form, justified_type="left-justified")

# -----------
# UPDATE 
# -----------
@bp.route("/update/<habit_id>", methods=["GET", "POST"])
def update(habit_id):
    form = UpdateHabitForm()
    if form.validate_on_submit():
        handle_update_habit(form, habit_id)
        return redirect(url_for("home.preferences"))
    
    habit = get_habit(habit_id)
    prepopulate_form(form, habit)
    return render_template("/components/forms/form.html", title=habit.name,  form=form, justified_type="left-justified")

# -----------
# DELETE 
# -----------
@bp.route("/delete/<habit_id>", methods=["GET", "DELETE"])
def delete(habit_id):
    handle_delete_habit(habit_id)
    return redirect(url_for("home.preferences"))


# ------------------------
# ADD HABITS TO CALENDAR 
# ------------------------
@bp.route("/addHabitsToCalendar", methods=["GET", "POST"])
def addHabitsToCalendar():
    user = get_user_from_thyme(session['email'])
    habits = get_habits()
    habit_strings = map(lambda habit: f"called {habit.name} for {habit.duration_min} min at {habit.ideal_start.strftime('%-I:%M %p')}", habits)
    answer_strings = map(lambda habit: f"{habit.name}", habits)

    for habit_string in habit_strings:
        prompt = f"Add an event to my calendar that repeats every weekday {habit_string}"
        answer_question(prompt, user) 
            
    answer = f"""
    I added these habits to your calendar: {(", ").join(answer_strings)}. 
    You might need to refresh the Google Calendar page or reopen the 
    Google Calendar App to see them."""
    
    return redirect(url_for("home.assistant", answer=answer))


# ------------------------
# EVENT HANDLERS
# ------------------------
def handle_add_habit(form):
    user = get_user_from_thyme(session['email'])
    habit = Habit(
       name = form.name.data,
       duration_min = form.duration_min.data,
       ideal_start = form.ideal_start.data,
       personal = form.personal.data,
       user_id = user.id
       )
    db.session.add(habit)
    db.session.commit()


def handle_delete_habit(habit_id):
    habit = get_habit(habit_id)
    db.session.delete(habit)
    db.session.commit()


def handle_update_habit(form, habit_id):
    habit = get_habit(habit_id)
    print('FORM', form.data )
    for field in form._fields.keys():
            data = getattr(getattr(form, field), 'data')
            if data != None and field != 'submit' and field != 'csrf_token' :
                print('attribute set', data)
                setattr(habit, field, data)
    db.session.commit()


# --------------------
# ERRORS
# --------------------
@bp.errorhandler(404)
@bp.errorhandler(500)
def page_not_found(error):
    if 'credentials' not in session:
      return redirect(url_for("home.index"))
    form = AskQuestionForm()
    return render_template("home.html", title="Home", form=form, form_type="one-line-form", justified_type="centered", answer=APOLOGY)
    

app/routes/home.py
from app.constants.general import APOLOGY
from app.models import db, User
from app.forms import AskQuestionForm, UpdatePreferencesForm
from app.functions.openai.answer_question import answer_question
from app.functions.openai.utils.save_chat import save_chat
from app.functions.thyme.helpers.habits import get_habits
from app.functions.thyme.helpers.user import get_user_from_thyme
from app.functions.thyme.helpers.forms import prepopulate_form
from flask import Blueprint, redirect, session, url_for, render_template

bp = Blueprint("home", __name__, url_prefix="/")

# --------------------
# WELCOME
# --------------------
@bp.route("/", methods=["GET"])
def index():
    return render_template("welcome.html", title="Welcome")


# --------------------
# HOME
# --------------------
@bp.route('/assistant/', methods=["GET", "POST"])
@bp.route('/assistant/<answer>', methods=["GET", "POST"])
def assistant(answer = None): 
  if 'credentials' not in session:
      return redirect(url_for("home.index"))
  
  form = AskQuestionForm()
  if form.validate_on_submit():
      answer = handleAnswerQuestion(form)
  return render_template("home.html", title="Home", form=form, form_type="one-line-form", justified_type="centered", answer=answer)


# --------------------
# PREFERENCES
# --------------------
@bp.route("/preferences", methods=["GET", "POST"])
def preferences():
    user =get_user_from_thyme(session['email'])
    habits = get_habits()
    return render_template("preferences.html", title="Preferences", habits=habits, user=user)


# --------------------
# UPDATE PREFERENCES
# --------------------
@bp.route("/updatePreferences", methods=["GET", "POST"])
def updatePreferences():
    form = UpdatePreferencesForm()
    if form.validate_on_submit():
       handleUpdatePreferences(form)
       return redirect(url_for("home.preferences"))
    user = get_user_from_thyme(session['email'])
    prepopulate_form(form, user)
    return render_template("/components/forms/form.html", title="Update Daily Schedule",  form=form, justified_type="left-justified")


# --------------------
# PRIVACY & TERMS
# --------------------
@bp.route("/privacy", methods=["GET"])
def privacy():
    return render_template("privacy.html")


@bp.route("/terms", methods=["GET"])
def terms():
    return render_template("terms.html")


# --------------------
# EVENT HANDLERS
# --------------------
def handleAnswerQuestion(form):
    prompt = form.question.data
    user = get_user_from_thyme(session['email'])
    messages = answer_question(prompt, user)
    save_chat(messages, user)
    answer = messages[len(messages) - 1]['content']
    return answer


def handleUpdatePreferences(form):
    user = get_user_from_thyme(session['email'])
 
    for field in form._fields.keys():
        data = form.data[field]
        if data != None and field != 'submit' and field != 'csrf_token' :
            setattr(user, field, data)
            db.session.execute(
                db.select(getattr(User, field))
                .where(User.id == user.id)).scalar_one()
    db.session.commit()


# --------------------
# ERRORS
# --------------------
@bp.errorhandler(404)
@bp.errorhandler(500)
def page_not_found(error):
    if 'credentials' not in session:
      return redirect(url_for("home.index"))
    form = AskQuestionForm()
    return render_template("home.html", title="Home", form=form, form_type="one-line-form", justified_type="centered", answer=APOLOGY)
    

app/routes/session.py
from app.constants.general import GOOGLE_CLIENT_CONFIG, SCOPES
from flask import Blueprint, redirect, request, session, url_for
import requests
import google_auth_oauthlib.flow
from app.functions.gcal.helpers.user import credentials_to_dict, get_email_from_google, get_user_from_google
from app.functions.gcal.helpers.datetime import get_timezone_from_google
from app.functions.thyme.helpers.user import create_user, get_user_from_thyme
bp = Blueprint("session", __name__, url_prefix="/session")

# ----------------
# LOGIN
# ----------------
@bp.route('/login', methods=["GET", "POST"])
def login():
  flow = google_auth_oauthlib.flow.Flow.from_client_config(client_config=GOOGLE_CLIENT_CONFIG, scopes=SCOPES )
  flow.redirect_uri = url_for('session.oauth2callback', _external=True)

  authorization_url, state = flow.authorization_url(
      access_type='offline',        # Enable offline access so you can refresh access token without re-prompting user for permission.
      include_granted_scopes='true' # Enable incremental authorizations
      )

  session['state'] = state 
  return redirect(authorization_url)


# ----------------
# OATH2 CALLBACK
# ----------------
@bp.route('/oauth2callback', methods=["GET", "POST"])
def oauth2callback():
  # Specify state when creating flow in the callback so it can be verified in authorization server response.
  # state = session['state']

  # Create Google Auth Flow object
  flow = google_auth_oauthlib.flow.Flow.from_client_config(client_config=GOOGLE_CLIENT_CONFIG, scopes=SCOPES)
  # flow = google_auth_oauthlib.flow.Flow.from_client_config(client_config=GOOGLE_CLIENT_CONFIG, scopes=SCOPES, state=state )

  # Set URL to redirect to after authorization
  flow.redirect_uri = url_for('session.oauth2callback', _external=True)

  # Use the authorization server's response to fetch the OAuth 2.0 tokens.
  authorization_response = request.url 
  flow.fetch_token(authorization_response=authorization_response)
  credentials = flow.credentials

  # Get user's email from Google
  email = get_email_from_google(credentials)

  # Store credentials & email in Flask session
  session['credentials'] = credentials_to_dict(credentials)
  session['email'] = email

  # Check to see if user exists in Thyme database
  try: 
    get_user_from_thyme(email)

  # If user doesn't exist, create user in Thyme database
  except:
    user = get_user_from_google(credentials)
    timezone = get_timezone_from_google(credentials)
    first_name = user['given_name']
    last_name = user['family_name']
    profile_picture = user['picture']

    create_user(email, first_name, last_name, profile_picture, timezone)
  return redirect(url_for('home.assistant'))


# ----------------
# LOGOUT
# ----------------
@bp.route('/logout')
def logout():
  if 'credentials' not in session: 
    return redirect(url_for("home.index"))
  
  # Revoke credentails from Google Auth
  requests.post('https://oauth2.googleapis.com/revoke',
      params={'token': session['credentials']['token']},
      headers = {'content-type': 'application/x-www-form-urlencoded'})
  
  # Delete credentials from Flask session
  if 'credentials' in session:
    del session['credentials']
    del session['email']

  return redirect(url_for("home.index"))


# --------------------
# ERRORS
# --------------------
@bp.errorhandler(404)
@bp.errorhandler(500)
def page_not_found(error):
  return redirect(url_for("home.index"))
    

app/templates/components/buttons/add_habit.html
<a href="{{ url_for('habit.add') }}">
    <button>Add Habit</button>
</a> 

app/templates/components/buttons/add_habits_to_gcal.html
<form method="post" action="{{ url_for('habit.addHabitsToCalendar') }}">
    <button class="icon-button" onclick="loading();">
        <img class="icon" src="static/images/google_icon.png" >
        Add Habits to Google Calendar
    </button>
</form>  

app/templates/components/buttons/add_habits_to_google_calendar.html
<form method="post" action="{{ url_for('habit.addHabitsToCalendar') }}">
    <button class="icon-button" onclick="loading();">
        <img class="icon" src="static/images/google_icon.png" >
        Add Habits to Google Calendar
    </button>
</form>  

app/templates/components/buttons/continue_with_google.html
<a href="{{ url_for('session.login') }}">
    <button class="icon-button">
        <img class="icon" src="static/images/google_icon.png">
        Login with Google
    </button>
</a>  

app/templates/components/buttons/delete.html
<a href="/habit/delete/{{habit.id}}">
    <button class="transparent-icon-button tooltip">
        <i class="fa fa-trash icon-white" style="font-size: 30px;"></i>
        <span class="tooltiptext">Delete</span>
    </button>
</a>

app/templates/components/buttons/edit.html
<a href="/habit/update/{{habit.id}}">
    <button class="transparent-icon-button tooltip">
        <i class="fa fa-edit icon-white" style="font-size: 30px;"></i>
        <span class="tooltiptext">Edit</span>
    </button>
</a>

app/templates/components/buttons/logout.html
<a href="{{ url_for('session.logout') }}">
    <button class="transparent-icon-button tooltip">
        <i class="fa fa-sign-out" style="font-size: 30px;"></i>
        <span class="tooltiptext">Logout</span>
    </button>
</a>

app/templates/components/buttons/open_gcal.html
<a href="https://calendar.google.com/" target="_blank">
    <button class="transparent-icon-button tooltip">
        <i class="fa fa-calendar" style="font-size: 30px;"></i>
        <span class="tooltiptext">Calendar</span>
</a>

app/templates/components/buttons/open_google_calendar.html
<a href="https://calendar.google.com/" target="_blank">
    <button class="transparent-icon-button tooltip">
        <i class="fa fa-calendar" style="font-size: 30px;"></i>
        <span class="tooltiptext">Calendar</span>
</a>

app/templates/components/buttons/preferences.html
<a href="{{ url_for('home.preferences') }}">
    <button class="transparent-icon-button tooltip">
        <i class="fa fa-gear" style="font-size: 30px;"></i>
        <span class="tooltiptext">Preferences</span>
</a>

app/templates/components/buttons/return_home.html
<a method="post" href="{{ url_for('home.assistant') }}">
    <button class="transparent-icon-button tooltip">
        <i class="fa fa-comments" style="font-size: 30px;"></i>
        <span class="tooltiptext">Assistant</span>
    </button>
</a>

app/templates/components/buttons/return_welcome.html
<a method="post" href="{{ url_for('home.index') }}">
    <button class="transparent-icon-button tooltip">
        <i class="fa fa-arrow-left" style="font-size: 30px;"></i>
        <span class="tooltiptext">Home</span>
    </button>
</a>